// In-memory notifications store. Real notifications are generated by backend
// events once the notifications API ships (docs/backend-api.md §9).

let notifications = [];

const listeners = new Set();

function emit() {
  listeners.forEach((fn) => fn());
}

export function subscribe(fn) {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

export function getNotifications() {
  return notifications;
}

export function markRead(id) {
  const n = notifications.find((x) => x.id === id);
  if (!n || n.read) return; // avoid pointless re-renders
  notifications = notifications.map((x) => (x.id === id ? { ...x, read: true } : x));
  emit();
}

export function markAllRead() {
  if (notifications.every((n) => n.read)) return;
  notifications = notifications.map((n) => (n.read ? n : { ...n, read: true }));
  emit();
}
